# Linear Algebra refresher


Plan:

- Vector operations
- Multiplication
  - Vector-vector multiplication
  - Matrix-vector multiplication
  - Matrix-matrix multiplication
- Identity matrix
- Inverse

In [1]:
import numpy as np

## Vector Operations

In [2]:
u = np.array([2,3,4,5])
print(f'Vector scalar multiplication: 2*u : {2*u}')

Vector scalar multiplication: 2*u : [ 4  6  8 10]
2


In [4]:
v = np.array([1,0,0,2])
print(f'Sum of two vectors u+v : {u+v}')
print(f'Element-wise multiplication of two vectors u*v : {u*v}')


Sum of two vectors u+v : [3 3 4 7]
Element-wise multiplication of two vectors u*v : [ 2  0  0 10]


### Multiplication

We perform vector-vector multiplication by using the dot product.

In [8]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0 
    for i in range(n):
        result = result + u[i]*v[i]
    
    return result

def vector_vector_multiplication2(u,v):
    assert u.shape[0] == v.shape[0]

    result = np.sum(u*v) 
    return result

In [9]:
vector_vector_multiplication(u,v) == u.dot(v) == vector_vector_multiplication2(u,v)

True

### Matrix-Vector multiplication

In [10]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

vect = np.array([1,0.5,2,1])

In [13]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    nrows = U.shape[0]
    result = np.zeros(nrows)
    for i in range(nrows):
        result[i]= vector_vector_multiplication(U[i],v)
    return result

In [16]:
print(matrix_vector_multiplication(U,vect))
U.dot(vect) == matrix_vector_multiplication(U,vect)


[20.   6.   8.5]


array([ True,  True,  True])

### Matrix-Matrix Multiplication

"Buch of matrix-vector multiplications" :) 

In [18]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [17]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    
    nrows,ncols = U.shape[0],V.shape[1]
    result = np.zeros((nrows,ncols))

    for i in range(ncols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi
    
    return result

In [20]:
print(matrix_matrix_multiplication(U,V))

U.dot(V) == matrix_matrix_multiplication(U,V)


[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Identity Matrix

Its a square matrix where in the diagonal we have 1s and zeros everywhere else. We have that
U.I = U or I.U = U

In [22]:
I = np.eye(3)
I.shape,V.shape

((3, 3), (4, 3))

In [24]:
V.dot(I) == V

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Matrix Inverse 

Only square matrices have inverse, so ncols==nrows. $A^1A = I$

In [26]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [28]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [29]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])